

### Create new Person
POST http://localhost:4004/person/Persons HTTP/1.1
Content-Type: application/json

{
    "ID": "8eb5964b-611e-4c8a-b19e-6a2f26f6ef13",
    "name1": "Charbel",
    "name2" : "Kisso",
    "personalNumber" : "198802105356",
    "contactInfo_phoneNumber": "0733642133",
    "type_ID": 1
}

### Get list of persons
GET http://localhost:4004/person/Persons HTTP/1.1
Content-Type: application/json

### Edit the Created Person
PATCH http://localhost:4004/person/Persons(8eb5964b-611e-4c8a-b19e-6a2f26f6ef13)
Content-Type: application/json

{
    "type_ID": 1
}

### Delete the Created Person
DELETE http://localhost:4004/person/Persons(8eb5964b-611e-4c8a-b19e-6a2f26f6ef13) HTTP/1.1